var allbeer = {};

allbeer['Ballast Point Brewing Co.'] = [
		{name: 'Aloha Sculpin',
		img: 'img/ballastpoint/rich-malty/01-sculpin-ipa.png',
		style: 'ipa',
		abv: '7.0',
		info: 'A hazy IPA with noles of guava and pineapple',
		traits: ['fruity','bitter'],
		id: '0'
		},
		{name: 'Manta Ray',
		img: 'img/ballastpoint/rich-malty/02-manta-ray-ipa.png',
		style: 'ipa',
		abv: '8.5',
		info: 'Light and dry on palate with big, hoppy flavor',
		traits: ['crisp','hop'],
		id: '1'
		},
		{name: 'Fathom',
		img: 'img/ballastpoint/rich-malty/03-fathom-ipa.png',
		style: 'ipa',
		abv: '6.6',
		info: 'IPA with hints of citrus and pine',
		traits: ['fruity','hop'],
		id: '2'
		},
		{name: 'Grapefruit Sculpin',
		img: 'img/ballastpoint/rich-malty/04-gf-sculpin-ipa.png',
		style: 'ipa',
		abv: '8.5',
		info: 'Signature IPA with bright, grapefruit punch',
		traits: ['fruity','hop'],
		id: '3'
		},
		{name: 'Watermelon Dorado',
		img: 'img/ballastpoint/rich-malty/05-melon-dorado.png',
		style: 'ipa',
		abv: '8.5',
		info: 'Double IPA with refreshing watermelon',
		traits: ['fruity','hop'],
		id: '4'
		},
		{name: 'Longfin Lager',
		img: 'img/ballastpoint/crisp-clear/01-longfin-lager.png',
		style: 'lager',
		abv: '5.2',
		info: 'A traditional Helles style lager that is light and refreshing',
		traits: ['crisp','malt'],
		id: '5'
		},
		{name: 'Dead Ringer',
		img: 'img/ballastpoint/crisp-clear/02-ca-kolsch.png',
		style: 'lager',
		abv: '5.8',
		info: 'Oktoberfest lager inspired by traditional Marren style',
		traits: ['crisp','malt'],
		id: '6'
		},
		{name: 'California Kolsch',
		img: 'img/ballastpoint/other/kolsch-tpk.png',
		style: 'kolsch',
		abv: '5.2',
		info: 'Kolsch style, light but complex with subdued fruitiness',
		traits: ['crisp','fruity','tart'],
		id: '7'
		},
		{name: 'Tart Peach Kolsch',
		img: 'img/ballastpoint/other/kolsch-tpk.png',
		style: 'kolsch',
		abv: '5.2',
		info: 'Hints of ripe peach with a refreshing tart finish',
		traits: ['crisp','fruity','tart'],
		id: '8'
		},
		{name: 'Victory at Sea',
		img: 'img/ballastpoint/other/porter-vas.png',
		style: 'porter',
		abv: '10',
		info: 'Imperial Porter with Cafe Calabria coffee vanilla',
		traits: ['malt','roasted'],
		id: '9'
		},
		{name: 'Victory at Sea PB',
		img: 'img/ballastpoint/other/porter-vasp.png',
		style: 'porter',
		abv: '10',
		info: 'Imperial Porter with peanuts',
		traits: ['malt','roasted','smoky'],
		id: '10'
		},
		{name: 'Bonito Blonde',
		img: 'img/ballastpoint/rich-malty/02-manta-ray-ipa.png',
		style: 'blonde',
		abv: '4.5',
		info: 'An American blonde ale w/ soft malt notes and slight yeast character',
		traits: ['crisp','malt'],
		id: '11'
		},
];

allbeer['Green Flash'] = [
		{name: 'Ideal Belgique',
		img: 'img/greenflash/lager/lager-ib.png',
		style: 'lager',
		abv: '9.0',
		info: 'Dual-yeast fermentation, spicy hops, and the addition of Muscovado brown sugar provide increased complexity and depth of flavor',
		traits: ['hop','roasted'],
		id: '12'
		},
		{name: 'Sea to Sea',
		img: 'img/greenflash/lager/lager-sts.png',
		style: 'lager',
		abv: '4.0',
		info: 'Subtle sweet malt with a light body, delicate fruity hop, notable lager yeast, and a crisp, clean finish',
		traits: ['crisp','fruity','hop','malt'],
		id: '13'
		},
		{name: 'Passion Fruit Kicker',
		img: 'img/greenflash/kolsch/kolsch-pfk.png',
		style: 'kolsch',
		abv: '5.5',
		info: 'Flavor has a prominent sweet tart passion fruit character that mingles with the Belgian fruit bowl esters',
		traits: ['crisp','fruity','tart'],
		id: '14'
		},
		{name: 'Blanc Tarte Barrique',
		img: 'img/greenflash/blonde/blonde-btb.png',
		style: 'blonde',
		abv: '4.5',
		info: 'This barrel-aged sour is fermented with Brettanomyces and Lactobacillus before extended barrel-aging in red and white wine barrels',
		traits: ['fruity','crisp'],
		id: '15'
		},
		{name: 'GFB',
		img: 'img/greenflash/blonde/blonde-gfb.png',
		style: 'blonde',
		abv: '4.8',
		info: 'A light, refreshing, crushable, with hints of honey and orange peel complemented by a mellow malt character',
		traits: ['crisp','fruity','malt'],
		id: '16'
		},
		{name: 'Cacow',
		img: 'img/greenflash/porter/porter-c.png',
		style: 'porter',
		abv: '6.3',
		info: 'Rich and full-bodied with notes of Swiss chocolate and mocha',
		traits: ['smoky','malt'],
		id: '17'
		},
		{name: 'Remix',
		img: 'img/greenflash/ipa/ipa-r.png',
		style: 'ipa',
		abv: '6.2',
		info: 'Very drinkable with thorough hop notes of fresh pine and citrus',
		traits: ['fruity','hop','tart'],
		id: '18'
		},
		{name: 'Soul Style',
		img: 'img/greenflash/ipa/ipa-ss.png',
		style: 'ipa',
		abv: '6.5',
		info: 'Starts with a mellow pale malt sweetness then transitions to pungent hop flavors with grassy notes and a lingering but clean bitter finish',
		traits: ['crisp','hop'],
		id: '19'
		},
		{name: 'Tropical DNA',
		img: 'img/greenflash/ipa/ipa-td.png',
		style: 'ipa',
		abv: '7.0',
		info: 'The palate is treated to bright, tropical fruit and citrus along with a soft, delicate mouthfeel',
		traits: ['crisp','fruity','hop'],
		id: '20'
		},
		{name: 'West Coast',
		img: 'img/greenflash/ipa/ipa-wc.png',
		style: 'ipa',
		abv: '8.1',
		info: 'Assertive, grapefruit zest bitterness supported by notes of dark caramel from British Crystal malt, finishes floral with dry woodsy hop notes',
		traits: ['hop','roasted'],
		id: '21'
		}
];

var breweries = [
		{name: 'Ballast Point Brewing Co.',
		img: 'img/locations/01-bp.png',
		location: 'La Jolla',
		address: '9045 Carroll Way'
		},
		{name: 'Duck Foot',
		img: 'img/locations/02-df.png',
		location: 'La Jolla',
		address: '8920 Kenmar Dr #210'
		},
		{name: 'Mike Hess',
		img: 'img/locations/04-mh.png',
		location: 'La Jolla',
		address: '7955 Silverton Ave #1201'
		},
		{name: 'Green Flash',
		img: 'img/locations/03-gf.png',
		location: 'La Jolla',
		address: '6550 Mira Mesa Blvd'
		},
		{name: 'San Diego Brewery',
		img: 'img/locations/brewery1.png',
		location: 'San Diego',
		address: '1234 Fake Address Dr'
		},
		{name: 'UCI Brewery',
		img: 'img/locations/brewery1.png',
		location: 'Irvine',
		address: '1212 Fake Again Dr'
		},
		{name: 'New York Brewery',
		img: 'img/locations/brewery1.png',
		location: 'New York',
		address: '7777 Also Fake Dr'
		}
];
